### ISSUE TITLE
entrevista

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/entrevista-gestion-de-proyectos#3]

**Comment by carlos-chrs** [comment]
[REPORTE_ENTREVISTA..pdf](https://github.com/SistemasTecTlaxiaco/entrevista-gestion-de-proyectos/files/9472513/REPORTE_ENTREVISTA.pdf)

**Comment by bg55-a** [comment]
Calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
